name: JS:CHECK

on: [push]

jobs: 
  js:check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
      
    steps: 
      - name: check
        run: npm run js:check    
    
    